development:
  adapter: postgresql
  database: patron_rankings_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: patron_rankings_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: patron_rankings_production
  pool: 5
  timeout: 5000
